name: platform-management-prod

on:
  push:
    paths:
      - 'parameters/platform-management-prod.json'
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/tmp-landingzone.yml
    with:
      topLevelManagementGroupName: gazelle
      location: francecentral
      parameterFile: ./parameters/platform-management-prod.json
    secrets: inherit